### ISSUE TITLE
help a newby with DTS files

### ISSUE THREAD

**Issue by cesaregiannetti** [unframework/licheepi-nano-buildroot#1]
This is my first experience with a kernel and my first Github issue, please excuse any misuse.
I'm struggling with this sentence from the README: "The custom kernel branch also includes a DTS file with support for 800x480 TFT resolution". I actually have a 800x480 display but I have no idea where to find such a DTS file... what do you mean by custom kernel branch? What am I missing? Could you please explain step-by-step what to do?

I have to say that the included 480 resolution works fine in the top-left corner of my display, with the rest behaving oddly, so +1 to you for having me (a complete kernel ignorant) compile and burn a working SD card for my Lichee pi nano.

**Comment by unframework** [comment]
Hi Cesare, thanks for trying out this repo, and I am happy to hear that it worked, even if partially!

My wording re: "custom kernel branch" is a bit confusing, yes. What I meant is that the kernel already includes a DTS file which supports the Lichee Pi with 800x480 TFT - a so-called "in-tree" DTS file. This is the file that was originally created by Lichee Pi folks/other contributors, actually - I switched away from using that file to my customized version.

To use it, one needs to tweak the config in several spots. I did not get around to fully documenting that change, but please see this commit for some hints: https://github.com/unframework/licheepi-nano-buildroot/commit/f3cf5f014e360a6002ad2ec07347aeaaab51209e. This was the code change that switched from original DTS file to my custom one: so in your case, you will want to "undo" the changes made in that commit. I.e. change the text in relevant files locally from green back to red. Then the usual `make` steps, etc.

I hope that makes sense, happy to clarify further!

**Comment by cesaregiannetti** [comment]
Hi Nick, thank you very much for the fast answer, makes perfect sense, I reverted your mods and it worked flowlessly first try. Sorry for the late feedback, I got sick in the meanwhile.
