### ISSUE TITLE
Is networking enabled?

### ISSUE THREAD

**Issue by gavan1** [unframework/licheepi-nano-buildroot#15]
There are no guides on the net for the wifi sd card adapter… But some that allow a Host pc to connect to the Licheepi Zero via a USB cable exposing usb0 network interface.

Is networking working for this image on the nano?

**Comment by unframework** [comment]
Hi there, I did not play with any networking yet. The kernel net subsystem flag is enabled (to allow core stuff like named sockets to work), but anything to do with networking hardware or USB compatibility layers is uncharted territory for me. Hopefully you figure out something - please comment here if you do!
