### ISSUE TITLE
Ethernet over usb

### ISSUE THREAD

**Issue by leonardowolf** [unframework/licheepi-nano-buildroot#17]
So, there is this capability:
https://wiki.sipeed.com/soft/Lichee/zh/Zero-Doc/application/otg2PC.html
Wich is present on the nano version of this board, i woud like to use that on my project but i can't make it work... also do not know where to start. 

Some help perhaps?

**Comment by muratozk** [comment]
@leonardowolf 
While in the root directory of your project
make linux-menuconfig
run the command then follow the steps in the tutorial. note: you may need to do a make clean.

**Comment by leonardowolf** [comment]
> 

it's not about the buildroot version but the u-boot as it seems

**Comment by unframework** [comment]
Hey, very belated response but I don't have any extra knowledge to share on this, sorry! Closing for now.
