### ISSUE TITLE
ImportError: No module named _libfdt

### ISSUE THREAD

**Issue by muratozk** [unframework/licheepi-nano-buildroot#7]
Hi @unframework . I test it latest version on vagrant. I have a little problem.

`vagrant@ubuntu-bionic:~/buildroot-2020.02$ python2 --version
Python 2.7.17

vagrant@ubuntu-bionic:~/buildroot-2020.02$ python --version
Python 2.7.17
`
How can i solve this problem ? Thank you.

> >>> uboot nano-v2018.01 Building
> PATH="/home/vagrant/buildroot-2020.02/output/host/bin:/home/vagrant/buildroot-2020.02/output/host/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" AR="/home/vagrant/buildroot-2020.02/output/host/bin/arm-buildroot-linux-gnueabi-ar" AS="/home/vagrant/buildroot-2020.02/output/host/bin/arm-buildroot-linux-gnueabi-as" LD="/home/vagrant/buildroot-2020.02/output/host/bin/arm-buildroot-linux-gnueabi-ld" NM="/home/vagrant/buildroot-2020.02/output/host/bin/arm-buildroot-linux-gnueabi-nm" CC="/home/vagrant/buildroot-2020.02/output/host/bin/arm-buildroot-linux-gnueabi-gcc" GCC="/home/vagrant/buildroot-2020.02/output/host/bin/arm-buildroot-linux-gnueabi-gcc" CPP="/home/vagrant/buildroot-2020.02/output/host/bin/arm-buildroot-linux-gnueabi-cpp" CXX="/home/vagrant/buildroot-2020.02/output/host/bin/arm-buildroot-linux-gnueabi-g++" FC="/home/vagrant/buildroot-2020.02/output/host/bin/arm-buildroot-linux-gnueabi-gfortran" F77="/home/vagrant/buildroot-2020.02/output/host/bin/arm-buildroot-linux-gnueabi-gfortran" RANLIB="/home/vagrant/buildroot-2020.02/output/host/bin/arm-buildroot-linux-gnueabi-ranlib" READELF="/home/vagrant/buildroot-2020.02/output/host/bin/arm-buildroot-linux-gnueabi-readelf" STRIP="/home/vagrant/buildroot-2020.02/output/host/bin/arm-buildroot-linux-gnueabi-strip" OBJCOPY="/home/vagrant/buildroot-2020.02/output/host/bin/arm-buildroot-linux-gnueabi-objcopy" OBJDUMP="/home/vagrant/buildroot-2020.02/output/host/bin/arm-buildroot-linux-gnueabi-objdump" AR_FOR_BUILD="/usr/bin/ar" AS_FOR_BUILD="/usr/bin/as" CC_FOR_BUILD="/usr/bin/gcc" GCC_FOR_BUILD="/usr/bin/gcc" CXX_FOR_BUILD="/usr/bin/g++" LD_FOR_BUILD="/usr/bin/ld" CPPFLAGS_FOR_BUILD="-I/home/vagrant/buildroot-2020.02/output/host/include" CFLAGS_FOR_BUILD="-O2 -I/home/vagrant/buildroot-2020.02/output/host/include" CXXFLAGS_FOR_BUILD="-O2 -I/home/vagrant/buildroot-2020.02/output/host/include" LDFLAGS_FOR_BUILD="-L/home/vagrant/buildroot-2020.02/output/host/lib -Wl,-rpath,/home/vagrant/buildroot-2020.02/output/host/lib" FCFLAGS_FOR_BUILD="" DEFAULT_ASSEMBLER="/home/vagrant/buildroot-2020.02/output/host/bin/arm-buildroot-linux-gnueabi-as" DEFAULT_LINKER="/home/vagrant/buildroot-2020.02/output/host/bin/arm-buildroot-linux-gnueabi-ld" CPPFLAGS="-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64" CFLAGS="-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os -g2 " CXXFLAGS="-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os -g2 " LDFLAGS="" FCFLAGS=" -Os -g2" FFLAGS=" -Os -g2" PKG_CONFIG="/home/vagrant/buildroot-2020.02/output/host/bin/pkg-config" STAGING_DIR="/home/vagrant/buildroot-2020.02/output/host/arm-buildroot-linux-gnueabi/sysroot" INTLTOOL_PERL=/usr/bin/perl /usr/bin/make  -C /home/vagrant/buildroot-2020.02/output/build/uboot-nano-v2018.01 CROSS_COMPILE="/home/vagrant/buildroot-2020.02/output/host/bin/arm-buildroot-linux-gnueabi-" ARCH=arm HOSTCC="/usr/bin/gcc -O2 -isystem /home/vagrant/buildroot-2020.02/output/host/include" HOSTLDFLAGS="-L/home/vagrant/buildroot-2020.02/output/host/lib -Wl,-rpath,/home/vagrant/buildroot-2020.02/output/host/lib"  all
>   CHK     include/config/uboot.release
>   CHK     include/generated/timestamp_autogenerated.h
>   UPD     include/generated/timestamp_autogenerated.h
>   PYMOD   scripts/dtc/pylibfdt/_libfdt.so
>   CHK     include/generated/version_autogenerated.h
>   CHK     include/generated/asm-offsets.h
>   CHK     include/generated/generic-asm-offsets.h
>   HOSTCC  tools/mkenvimage.o
>   HOSTCC  tools/fit_image.o
>   HOSTCC  tools/image-host.o
>   HOSTCC  tools/dumpimage.o
>   HOSTCC  tools/mkimage.o
>   CHK     include/config.h
>   HOSTCC  tools/sunxi-spl-image-builder.o
>   CFG     u-boot.cfg
>   HOSTLD  tools/mkenvimage
>   HOSTLD  tools/dumpimage
>   HOSTLD  tools/sunxi-spl-image-builder
>   HOSTLD  tools/mkimage
>   CC      common/main.o
>   CC      cmd/version.o
>   LD      cmd/built-in.o
>   LD      common/built-in.o
>   CC      lib/smbios.o
>   CC      lib/display_options.o
> In file included from include/div64.h:38,
>                  from lib/display_options.c:10:
> include/linux/log2.h:19:1: warning: ignoring attribute ‘noreturn’ because it conflicts with attribute ‘const’ [-Wattributes]
>  int ____ilog2_NaN(void);
>  ^~~
>   CC      lib/efi_loader/helloworld.o
>   LD      lib/efi_loader/helloworld_efi.so
>   OBJCOPY lib/efi_loader/helloworld.efi
> rm lib/efi_loader/helloworld.o lib/efi_loader/helloworld_efi.so
>   LD      lib/built-in.o
>   LD      u-boot
>   OBJCOPY u-boot-nodtb.bin
>   OBJCOPY u-boot.srec
>   SYM     u-boot.sym
> make[4]: 'arch/arm/dts/suniv-f1c100s-licheepi-nano.dtb' is up to date.
>   CAT     u-boot-dtb.bin
>   COPY    u-boot.bin
>   MKIMAGE u-boot.img
>   MKIMAGE u-boot-dtb.img
>   CC      spl/common/spl/spl.o
> In file included from include/div64.h:38,
>                  from include/linux/mtd/mtd.h:24,
>                  from include/nand.h:34,
>                  from common/spl/spl.c:15:
> include/linux/log2.h:19:1: warning: ignoring attribute ‘noreturn’ because it conflicts with attribute ‘const’ [-Wattributes]
>  int ____ilog2_NaN(void);
>  ^~~
>   CC      spl/lib/display_options.o
> In file included from include/div64.h:38,
>                  from lib/display_options.c:10:
> include/linux/log2.h:19:1: warning: ignoring attribute ‘noreturn’ because it conflicts with attribute ‘const’ [-Wattributes]
>  int ____ilog2_NaN(void);
>  ^~~
>   LD      spl/common/spl/built-in.o
>   LD      spl/lib/built-in.o
>   LD      spl/u-boot-spl
>   OBJCOPY spl/u-boot-spl-nodtb.bin
>   COPY    spl/u-boot-spl.bin
>   MKSUNXI spl/sunxi-spl.bin
>   BINMAN  u-boot-sunxi-with-spl.bin
> Traceback (most recent call last):
>   File "./tools/binman/binman", line 32, in <module>
>     import control
>   File "/home/vagrant/buildroot-2020.02/output/build/uboot-nano-v2018.01/tools/binman/control.py", line 16, in <module>
>     import fdt
>   File "/home/vagrant/buildroot-2020.02/output/build/uboot-nano-v2018.01/tools/binman/../dtoc/fdt.py", line 13, in <module>
>     import libfdt
>   File "scripts/dtc/pylibfdt/libfdt.py", line 17, in <module>
>     _libfdt = swig_import_helper()
>   File "scripts/dtc/pylibfdt/libfdt.py", line 16, in swig_import_helper
>     return importlib.import_module('_libfdt')
>   File "/home/vagrant/buildroot-2020.02/output/host/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
> ImportError: No module named _libfdt
> Makefile:1148: recipe for target 'u-boot-sunxi-with-spl.bin' failed
> make[2]: *** [u-boot-sunxi-with-spl.bin] Error 1
> package/pkg-generic.mk:266: recipe for target '/home/vagrant/buildroot-2020.02/output/build/uboot-nano-v2018.01/.stamp_built' failed
> make[1]: *** [/home/vagrant/buildroot-2020.02/output/build/uboot-nano-v2018.01/.stamp_built] Error 2
> Makefile:84: recipe for target '_all' failed
> make: *** [_all] Error 2

**Comment by unframework** [comment]
Hi Murat, that's odd - I have not encountered this when I was rebuilding a few days ago. Could try to install python3 as well (`python3-dev` and `python3-distutils`). Please let me know if that makes a difference...

**Comment by muratozk** [comment]
Unfortunately nothing has changed. I guess there is a problem with Uboot. More precisely, it stems from the python script.

**Comment by muratozk** [comment]
Hi @unframework . Today try it clean install Ubuntu 16.04.7. After follow steps.
`apt-get update
apt-get install -y wget tar git curl gcc-arm-none-eabi flex bison build-essential libncurses5-dev python swig python-dev bc libusb-1.0-0-dev pkg-config libssl-dev libc6-i386 lib32stdc++6 lib32z1 cpio unzip mtd-utils module-init-tools squashfs-tools


BR2_EXTERNAL=/home/user/licheepi-nano-buildroot make licheepi_nano_defconfig

make menuconfig one more customize. Before trying python3 and modules

Target packages  --->   Interpreter languages and scripting   --->   Python 2 <------Select
Target packages  --->   Interpreter languages and scripting   --->    core python modules  <------Select


`

After start make. Current time X.org and other peripheral configuration. Test successfull after sharing latest version gui config.

**Comment by JarrettR** [comment]
fyi in `make menuconfig`, you need to go to `bootloaders` and check `u-Boot needs dtc`, host python 2.x, and `U-Boot needs pylibfdt`

Remember to `make clean` before you build again, just targeting uboot doesn't do it.
